# Generated by Django 2.1.3 on 2019-01-07 07:10

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20181112_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('introduction', models.TextField(default='我的相册', max_length=256)),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
                ('is_visible', models.BooleanField(default=True)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('mod_data', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
                ('alt', models.CharField(blank=True, default='', max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('thumb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='album.Album')),
            ],
        ),
    ]
